### ISSUE TITLE
Setup Django Backend

### ISSUE THREAD

**Issue by Moosaa95** [Moosaa95/online-bookstore#1]
1. Create a new Django project and app.
2. Define models for books and user profiles.
3. Set up the database and configure user authentication.
4. Create Django admin interfaces for managing books and user profiles.

**Comment by Mohammadreza-Alizadeh** [comment]
Hi friend
can i work on this?

**Comment by Moosaa95** [comment]
> Hi friend can i work on this?

yes sure
